name: tic_tac_toe
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  build: ^2.3.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  google_fonts: ^2.3.2
  lottie: ^1.3.0

dev_dependencies:
  build_runner: null
  flutter_gen_runner: null
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Amity
      fonts:
        - asset: assets/fonts/amity.ttf
